### ISSUE TITLE
Posti Shipping -lisäosa ei ole yhteensopiva Woocommercen "lohkoeditorikassan" kanssa

### ISSUE THREAD

**Issue by Zameleon** [Seravo/woo-pakettikauppa#378]
Posti Shipping -lisäosa ei ole yhteensopiva Woocommercen "lohkoeditorikassan" kanssa, joka on nyt Woocommercen oletus. Vieläkö tätä kyseistä lisäosaa kehitetään?

**Comment by joosev** [comment]
Plugari päivitetään kyllä ja lohkoeditorin tuki on kehityksessä.
