### ISSUE TITLE
Woocommerce Posti Shipping ongelma

### ISSUE THREAD

**Issue by mattip93** [Seravo/woo-pakettikauppa#382]
I am making e-commerce website and I tried to Install Post Shipping plugin, and I have all the keys etc, but it's saying :"Bad credentials code 401" , API avaimet tilattu 2 kertaa, mutta silti herjaa Bad Credentials, kokeiltu ihan puhtaalle woocommerce sivulle niin herjaa samaa. Onkohan jotain vikaa?

**Comment by mattip93** [comment]
Sain API avaimet toimimaan, kun eräs ihminen sitä koodasi. Mutta Noutopiste hakua ei näy kassalle? Onko siis softassa joku virhe vai miten saisi toimimaan?

**Comment by muu2388** [comment]
I also have the same problem, no pick-up points showed up for selection in the checkout. (API keys applying and looks like working fine)

**Comment by mattip93** [comment]
Okey good to know, so the problem is on Plugin... Because I did everything correct and also made new blank site and put this there, so there is problem in plugin..

**Comment by mattip93** [comment]
> I also have the same problem, no pick-up points showed up for selection in the checkout. (API keys applying and looks like working fine)

Muu2388, if you find solution or know what was the problem let me know also? I also let you know if I can get it working😅

**Comment by muu2388** [comment]
I hope this issue is fixed soon. However, I have decided to use other service instead of waiting here for updates.

**Comment by joosev** [comment]
Please contact customer service. Please also provide screenshot from tools -> posti diagnostic tool page for the customer service.

pickup point search tested and works OK.

**Comment by mattip93** [comment]
i can also send pictures, but its really not working..
