### ISSUE TITLE
Woocommerce postilisäosa ei toimi.

### ISSUE THREAD

**Issue by mattip93** [Seravo/woo-pakettikauppa#383]
Woocommerce postilisäosa ei toimi. Eli se ei hae automaattisesti postinumeron perusteellä esimerkiksi Lähimpiä r-kioskeja/pakettiautomaatteja jne.. saisiko tämän korjattua?

**Comment by joosev** [comment]
Hyvin näyttäisi toimivan. Suosittelen ongelmatilanteissa ottamaan aina yhteyttä asiakaspalveluun. Tätä sivustoa luetaan ehkä korkeintaan kerran kuukaudessa.

**Comment by mattip93** [comment]
Otettu yhteyttä, tosiaan ei vieläkään toimi ja mitä kysellyt nii kaikilla on sama ongelma. Kassalla kun laittaa osoitteen niin ei tule vaihtoehtoja että voisi valita esim. Pakettiautomaatin.
